// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ckv_proto.proto

#ifndef PROTOBUF_ckv_5fproto_2eproto__INCLUDED
#define PROTOBUF_ckv_5fproto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protoSpec {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ckv_5fproto_2eproto();
void protobuf_AssignDesc_ckv_5fproto_2eproto();
void protobuf_ShutdownFile_ckv_5fproto_2eproto();

class DelMessage;
class GetMessage;
class PutMessage;
class Reply;
class Request;

enum Request_Operation {
  Request_Operation_GET = 1,
  Request_Operation_PUT = 2,
  Request_Operation_DEL = 3
};
bool Request_Operation_IsValid(int value);
const Request_Operation Request_Operation_Operation_MIN = Request_Operation_GET;
const Request_Operation Request_Operation_Operation_MAX = Request_Operation_DEL;
const int Request_Operation_Operation_ARRAYSIZE = Request_Operation_Operation_MAX + 1;

const ::google::protobuf::EnumDescriptor* Request_Operation_descriptor();
inline const ::std::string& Request_Operation_Name(Request_Operation value) {
  return ::google::protobuf::internal::NameOfEnum(
    Request_Operation_descriptor(), value);
}
inline bool Request_Operation_Parse(
    const ::std::string& name, Request_Operation* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Request_Operation>(
    Request_Operation_descriptor(), name, value);
}
// ===================================================================

class GetMessage : public ::google::protobuf::Message {
 public:
  GetMessage();
  virtual ~GetMessage();

  GetMessage(const GetMessage& from);

  inline GetMessage& operator=(const GetMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetMessage& default_instance();

  void Swap(GetMessage* other);

  // implements Message ----------------------------------------------

  inline GetMessage* New() const { return New(NULL); }

  GetMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetMessage& from);
  void MergeFrom(const GetMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string key = 1;
  bool has_key() const;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // @@protoc_insertion_point(class_scope:protoSpec.GetMessage)
 private:
  inline void set_has_key();
  inline void clear_has_key();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  friend void  protobuf_AddDesc_ckv_5fproto_2eproto();
  friend void protobuf_AssignDesc_ckv_5fproto_2eproto();
  friend void protobuf_ShutdownFile_ckv_5fproto_2eproto();

  void InitAsDefaultInstance();
  static GetMessage* default_instance_;
};
// -------------------------------------------------------------------

class PutMessage : public ::google::protobuf::Message {
 public:
  PutMessage();
  virtual ~PutMessage();

  PutMessage(const PutMessage& from);

  inline PutMessage& operator=(const PutMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PutMessage& default_instance();

  void Swap(PutMessage* other);

  // implements Message ----------------------------------------------

  inline PutMessage* New() const { return New(NULL); }

  PutMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PutMessage& from);
  void MergeFrom(const PutMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PutMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string key = 1;
  bool has_key() const;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // required string value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:protoSpec.PutMessage)
 private:
  inline void set_has_key();
  inline void clear_has_key();
  inline void set_has_value();
  inline void clear_has_value();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  friend void  protobuf_AddDesc_ckv_5fproto_2eproto();
  friend void protobuf_AssignDesc_ckv_5fproto_2eproto();
  friend void protobuf_ShutdownFile_ckv_5fproto_2eproto();

  void InitAsDefaultInstance();
  static PutMessage* default_instance_;
};
// -------------------------------------------------------------------

class DelMessage : public ::google::protobuf::Message {
 public:
  DelMessage();
  virtual ~DelMessage();

  DelMessage(const DelMessage& from);

  inline DelMessage& operator=(const DelMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DelMessage& default_instance();

  void Swap(DelMessage* other);

  // implements Message ----------------------------------------------

  inline DelMessage* New() const { return New(NULL); }

  DelMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DelMessage& from);
  void MergeFrom(const DelMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DelMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string key = 1;
  bool has_key() const;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // @@protoc_insertion_point(class_scope:protoSpec.DelMessage)
 private:
  inline void set_has_key();
  inline void clear_has_key();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  friend void  protobuf_AddDesc_ckv_5fproto_2eproto();
  friend void protobuf_AssignDesc_ckv_5fproto_2eproto();
  friend void protobuf_ShutdownFile_ckv_5fproto_2eproto();

  void InitAsDefaultInstance();
  static DelMessage* default_instance_;
};
// -------------------------------------------------------------------

class Request : public ::google::protobuf::Message {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  void Swap(Request* other);

  // implements Message ----------------------------------------------

  inline Request* New() const { return New(NULL); }

  Request* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Request_Operation Operation;
  static const Operation GET = Request_Operation_GET;
  static const Operation PUT = Request_Operation_PUT;
  static const Operation DEL = Request_Operation_DEL;
  static inline bool Operation_IsValid(int value) {
    return Request_Operation_IsValid(value);
  }
  static const Operation Operation_MIN =
    Request_Operation_Operation_MIN;
  static const Operation Operation_MAX =
    Request_Operation_Operation_MAX;
  static const int Operation_ARRAYSIZE =
    Request_Operation_Operation_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Operation_descriptor() {
    return Request_Operation_descriptor();
  }
  static inline const ::std::string& Operation_Name(Operation value) {
    return Request_Operation_Name(value);
  }
  static inline bool Operation_Parse(const ::std::string& name,
      Operation* value) {
    return Request_Operation_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .protoSpec.Request.Operation op = 1;
  bool has_op() const;
  void clear_op();
  static const int kOpFieldNumber = 1;
  ::protoSpec::Request_Operation op() const;
  void set_op(::protoSpec::Request_Operation value);

  // optional .protoSpec.GetMessage get = 2;
  bool has_get() const;
  void clear_get();
  static const int kGetFieldNumber = 2;
  const ::protoSpec::GetMessage& get() const;
  ::protoSpec::GetMessage* mutable_get();
  ::protoSpec::GetMessage* release_get();
  void set_allocated_get(::protoSpec::GetMessage* get);

  // optional .protoSpec.PutMessage put = 3;
  bool has_put() const;
  void clear_put();
  static const int kPutFieldNumber = 3;
  const ::protoSpec::PutMessage& put() const;
  ::protoSpec::PutMessage* mutable_put();
  ::protoSpec::PutMessage* release_put();
  void set_allocated_put(::protoSpec::PutMessage* put);

  // optional .protoSpec.DelMessage del = 4;
  bool has_del() const;
  void clear_del();
  static const int kDelFieldNumber = 4;
  const ::protoSpec::DelMessage& del() const;
  ::protoSpec::DelMessage* mutable_del();
  ::protoSpec::DelMessage* release_del();
  void set_allocated_del(::protoSpec::DelMessage* del);

  // @@protoc_insertion_point(class_scope:protoSpec.Request)
 private:
  inline void set_has_op();
  inline void clear_has_op();
  inline void set_has_get();
  inline void clear_has_get();
  inline void set_has_put();
  inline void clear_has_put();
  inline void set_has_del();
  inline void clear_has_del();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::protoSpec::GetMessage* get_;
  ::protoSpec::PutMessage* put_;
  ::protoSpec::DelMessage* del_;
  int op_;
  friend void  protobuf_AddDesc_ckv_5fproto_2eproto();
  friend void protobuf_AssignDesc_ckv_5fproto_2eproto();
  friend void protobuf_ShutdownFile_ckv_5fproto_2eproto();

  void InitAsDefaultInstance();
  static Request* default_instance_;
};
// -------------------------------------------------------------------

class Reply : public ::google::protobuf::Message {
 public:
  Reply();
  virtual ~Reply();

  Reply(const Reply& from);

  inline Reply& operator=(const Reply& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Reply& default_instance();

  void Swap(Reply* other);

  // implements Message ----------------------------------------------

  inline Reply* New() const { return New(NULL); }

  Reply* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Reply& from);
  void MergeFrom(const Reply& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Reply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 status = 1;
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // optional string value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:protoSpec.Reply)
 private:
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_value();
  inline void clear_has_value();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  ::google::protobuf::int32 status_;
  friend void  protobuf_AddDesc_ckv_5fproto_2eproto();
  friend void protobuf_AssignDesc_ckv_5fproto_2eproto();
  friend void protobuf_ShutdownFile_ckv_5fproto_2eproto();

  void InitAsDefaultInstance();
  static Reply* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// GetMessage

// required string key = 1;
inline bool GetMessage::has_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetMessage::set_has_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetMessage::clear_has_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetMessage::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_key();
}
inline const ::std::string& GetMessage::key() const {
  // @@protoc_insertion_point(field_get:protoSpec.GetMessage.key)
  return key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetMessage::set_key(const ::std::string& value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protoSpec.GetMessage.key)
}
inline void GetMessage::set_key(const char* value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protoSpec.GetMessage.key)
}
inline void GetMessage::set_key(const char* value, size_t size) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protoSpec.GetMessage.key)
}
inline ::std::string* GetMessage::mutable_key() {
  set_has_key();
  // @@protoc_insertion_point(field_mutable:protoSpec.GetMessage.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetMessage::release_key() {
  clear_has_key();
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetMessage::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    set_has_key();
  } else {
    clear_has_key();
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:protoSpec.GetMessage.key)
}

// -------------------------------------------------------------------

// PutMessage

// required string key = 1;
inline bool PutMessage::has_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PutMessage::set_has_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PutMessage::clear_has_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PutMessage::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_key();
}
inline const ::std::string& PutMessage::key() const {
  // @@protoc_insertion_point(field_get:protoSpec.PutMessage.key)
  return key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PutMessage::set_key(const ::std::string& value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protoSpec.PutMessage.key)
}
inline void PutMessage::set_key(const char* value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protoSpec.PutMessage.key)
}
inline void PutMessage::set_key(const char* value, size_t size) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protoSpec.PutMessage.key)
}
inline ::std::string* PutMessage::mutable_key() {
  set_has_key();
  // @@protoc_insertion_point(field_mutable:protoSpec.PutMessage.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PutMessage::release_key() {
  clear_has_key();
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PutMessage::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    set_has_key();
  } else {
    clear_has_key();
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:protoSpec.PutMessage.key)
}

// required string value = 2;
inline bool PutMessage::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PutMessage::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PutMessage::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PutMessage::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
inline const ::std::string& PutMessage::value() const {
  // @@protoc_insertion_point(field_get:protoSpec.PutMessage.value)
  return value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PutMessage::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protoSpec.PutMessage.value)
}
inline void PutMessage::set_value(const char* value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protoSpec.PutMessage.value)
}
inline void PutMessage::set_value(const char* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protoSpec.PutMessage.value)
}
inline ::std::string* PutMessage::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:protoSpec.PutMessage.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PutMessage::release_value() {
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PutMessage::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:protoSpec.PutMessage.value)
}

// -------------------------------------------------------------------

// DelMessage

// required string key = 1;
inline bool DelMessage::has_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DelMessage::set_has_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DelMessage::clear_has_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DelMessage::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_key();
}
inline const ::std::string& DelMessage::key() const {
  // @@protoc_insertion_point(field_get:protoSpec.DelMessage.key)
  return key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DelMessage::set_key(const ::std::string& value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protoSpec.DelMessage.key)
}
inline void DelMessage::set_key(const char* value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protoSpec.DelMessage.key)
}
inline void DelMessage::set_key(const char* value, size_t size) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protoSpec.DelMessage.key)
}
inline ::std::string* DelMessage::mutable_key() {
  set_has_key();
  // @@protoc_insertion_point(field_mutable:protoSpec.DelMessage.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DelMessage::release_key() {
  clear_has_key();
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DelMessage::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    set_has_key();
  } else {
    clear_has_key();
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:protoSpec.DelMessage.key)
}

// -------------------------------------------------------------------

// Request

// required .protoSpec.Request.Operation op = 1;
inline bool Request::has_op() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request::set_has_op() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request::clear_has_op() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request::clear_op() {
  op_ = 1;
  clear_has_op();
}
inline ::protoSpec::Request_Operation Request::op() const {
  // @@protoc_insertion_point(field_get:protoSpec.Request.op)
  return static_cast< ::protoSpec::Request_Operation >(op_);
}
inline void Request::set_op(::protoSpec::Request_Operation value) {
  assert(::protoSpec::Request_Operation_IsValid(value));
  set_has_op();
  op_ = value;
  // @@protoc_insertion_point(field_set:protoSpec.Request.op)
}

// optional .protoSpec.GetMessage get = 2;
inline bool Request::has_get() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Request::set_has_get() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Request::clear_has_get() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Request::clear_get() {
  if (get_ != NULL) get_->::protoSpec::GetMessage::Clear();
  clear_has_get();
}
inline const ::protoSpec::GetMessage& Request::get() const {
  // @@protoc_insertion_point(field_get:protoSpec.Request.get)
  return get_ != NULL ? *get_ : *default_instance_->get_;
}
inline ::protoSpec::GetMessage* Request::mutable_get() {
  set_has_get();
  if (get_ == NULL) {
    get_ = new ::protoSpec::GetMessage;
  }
  // @@protoc_insertion_point(field_mutable:protoSpec.Request.get)
  return get_;
}
inline ::protoSpec::GetMessage* Request::release_get() {
  clear_has_get();
  ::protoSpec::GetMessage* temp = get_;
  get_ = NULL;
  return temp;
}
inline void Request::set_allocated_get(::protoSpec::GetMessage* get) {
  delete get_;
  get_ = get;
  if (get) {
    set_has_get();
  } else {
    clear_has_get();
  }
  // @@protoc_insertion_point(field_set_allocated:protoSpec.Request.get)
}

// optional .protoSpec.PutMessage put = 3;
inline bool Request::has_put() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Request::set_has_put() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Request::clear_has_put() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Request::clear_put() {
  if (put_ != NULL) put_->::protoSpec::PutMessage::Clear();
  clear_has_put();
}
inline const ::protoSpec::PutMessage& Request::put() const {
  // @@protoc_insertion_point(field_get:protoSpec.Request.put)
  return put_ != NULL ? *put_ : *default_instance_->put_;
}
inline ::protoSpec::PutMessage* Request::mutable_put() {
  set_has_put();
  if (put_ == NULL) {
    put_ = new ::protoSpec::PutMessage;
  }
  // @@protoc_insertion_point(field_mutable:protoSpec.Request.put)
  return put_;
}
inline ::protoSpec::PutMessage* Request::release_put() {
  clear_has_put();
  ::protoSpec::PutMessage* temp = put_;
  put_ = NULL;
  return temp;
}
inline void Request::set_allocated_put(::protoSpec::PutMessage* put) {
  delete put_;
  put_ = put;
  if (put) {
    set_has_put();
  } else {
    clear_has_put();
  }
  // @@protoc_insertion_point(field_set_allocated:protoSpec.Request.put)
}

// optional .protoSpec.DelMessage del = 4;
inline bool Request::has_del() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Request::set_has_del() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Request::clear_has_del() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Request::clear_del() {
  if (del_ != NULL) del_->::protoSpec::DelMessage::Clear();
  clear_has_del();
}
inline const ::protoSpec::DelMessage& Request::del() const {
  // @@protoc_insertion_point(field_get:protoSpec.Request.del)
  return del_ != NULL ? *del_ : *default_instance_->del_;
}
inline ::protoSpec::DelMessage* Request::mutable_del() {
  set_has_del();
  if (del_ == NULL) {
    del_ = new ::protoSpec::DelMessage;
  }
  // @@protoc_insertion_point(field_mutable:protoSpec.Request.del)
  return del_;
}
inline ::protoSpec::DelMessage* Request::release_del() {
  clear_has_del();
  ::protoSpec::DelMessage* temp = del_;
  del_ = NULL;
  return temp;
}
inline void Request::set_allocated_del(::protoSpec::DelMessage* del) {
  delete del_;
  del_ = del;
  if (del) {
    set_has_del();
  } else {
    clear_has_del();
  }
  // @@protoc_insertion_point(field_set_allocated:protoSpec.Request.del)
}

// -------------------------------------------------------------------

// Reply

// required int32 status = 1;
inline bool Reply::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Reply::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Reply::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Reply::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 Reply::status() const {
  // @@protoc_insertion_point(field_get:protoSpec.Reply.status)
  return status_;
}
inline void Reply::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:protoSpec.Reply.status)
}

// optional string value = 2;
inline bool Reply::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Reply::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Reply::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Reply::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
inline const ::std::string& Reply::value() const {
  // @@protoc_insertion_point(field_get:protoSpec.Reply.value)
  return value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Reply::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protoSpec.Reply.value)
}
inline void Reply::set_value(const char* value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protoSpec.Reply.value)
}
inline void Reply::set_value(const char* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protoSpec.Reply.value)
}
inline ::std::string* Reply::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:protoSpec.Reply.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Reply::release_value() {
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Reply::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:protoSpec.Reply.value)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protoSpec

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::protoSpec::Request_Operation> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protoSpec::Request_Operation>() {
  return ::protoSpec::Request_Operation_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ckv_5fproto_2eproto__INCLUDED
